#!/bin/sh
TEST_NAME=$1
EXPECTED_SCREENSHOT=$2 
ACTUAL_SCREENSHOT=$3

EXPECTED_RESULTS_PATH="$UITESTS_DIR/expectedResults/$TEST_NAME"
ACTUAL_RESULTS_PATH="$UITESTS_DIR/results/$TEST_NAME/Run 1" 

COMPARE=$(which compare)

$COMPARE -metric AE "$EXPECTED_RESULTS_PATH"/"$EXPECTED_SCREENSHOT".png "$ACTUAL_RESULTS_PATH"/"$ACTUAL_SCREENSHOT".png "$UITESTS_DIR"/diff.png

exit 0
